---
- name: install git and clone repo
  hosts: app
  tasks:
    - name: install git 
      apt:
        name: git
        state: present

    - name: cloning repo
      git:
        repo: https://github.com/prabha442/terraformnew.git
        dest: /home/ubuntu/git/dir111
        

