---
- name: setup ci-cd
  hosts: app
  tasks:
    - name: install s/w's for jenkins ci-cd
      apt:
        name: "{{item}}"
        state: present
        update_cache: no
      with_items:
        - openjdk-8-jdk
        - git
        - maven
    - name: isnatll jenkins
      get_url:
        url: https://get.jenkins.io/war-stable/2.332.1/jenkins.war
        dest: /tmp
- name: configure QA and PROD 
  hosts: web
  tasks:
    - name: install tomcat9 and tomcat9-admin
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - tomcat9
        - tomcat9-admin
    - name: copy the file to creta user and password tomcat
      copy:
        src: /home/ubuntu/playbooks/tomcat-users.xml
        dest: /etc/tomcat9/tomcat-users.xml




