---
- name: install s/w using looping concept
  hosts: app
  tasks:
    - name: install multiple s/w's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree,b: absent,c: no}
        - {a: git,b: present,c: no}
        - {a: openjdk-8-jdk,b: absent,c: no}
        - {a: maven,b: absent,c: no}
        - {a: firewalld,b: absent,c: no}
